from __future__ import annotations

from .connection import get_connection
from .settings import get_setting, set_setting, delete_setting
from .credentials import (
    bank_credentials_configured,
    build_credentials_scope,
    delete_bank_account,
    delete_bank_credentials,
    list_bank_accounts,
    list_bank_credentials,
    load_bank_credentials,
    save_bank_credentials,
    update_bank_account,
    upsert_bank_accounts,
)
from .references import (
    create_empfaengerkonto_record,
    create_kontoinhaber_record,
    delete_empfaengerkonto_record,
    delete_kontoinhaber_record,
    get_empfaengerkonto_record,
    get_kontoinhaber_record,
    list_empfaengerkonten_records,
    list_iban_kontoinhaber_references,
    list_kontoinhaber_iban_mappings,
    list_kontoinhaber_records,
    update_empfaengerkonto_record,
    update_kontoinhaber_iban_mapping,
    update_kontoinhaber_record,
)
from .categories import (
    create_category_record,
    delete_category_record,
    get_category_record,
    list_categories,
    update_category_record,
    update_transaction_category,
    update_transactions_category_batch,
)
from .schema import initialize_database
from .transactions import delete_transaction, delete_transactions_batch, fetch_latest_transaction, fetch_transaction_balance, fetch_transactions, insert_balance_adjustment, insert_transactions, row_to_dict, to_row_payload, update_transaction_note

__all__ = [
    "bank_credentials_configured",
    "build_credentials_scope",
    "create_category_record",
    "create_empfaengerkonto_record",
    "delete_bank_account",
    "delete_bank_credentials",
    "delete_category_record",
    "delete_setting",
    "get_setting",
    "delete_transaction",
    "delete_transactions_batch",
    "delete_empfaengerkonto_record",
    "create_kontoinhaber_record",
    "delete_kontoinhaber_record",
    "fetch_latest_transaction",
    "fetch_transaction_balance",
    "fetch_transactions",
    "get_connection",
    "get_category_record",
    "get_empfaengerkonto_record",
    "get_kontoinhaber_record",
    "initialize_database",
    "list_empfaengerkonten_records",
    "list_categories",
    "list_bank_accounts",
    "insert_transactions",
    "insert_balance_adjustment",
    "list_iban_kontoinhaber_references",
    "list_kontoinhaber_iban_mappings",
    "list_kontoinhaber_records",
    "list_bank_credentials",
    "load_bank_credentials",
    "row_to_dict",
    "save_bank_credentials",
    "set_setting",
    "update_category_record",
    "update_empfaengerkonto_record",
    "update_bank_account",
    "update_kontoinhaber_iban_mapping",
    "update_kontoinhaber_record",
    "update_transaction_category",
    "update_transactions_category_batch",
    "update_transaction_note",
    "upsert_bank_accounts",
    "to_row_payload",
]
